---
Formação Cientista de Dados 
Amostragem Simples
---
150 amostras, de zero e 1, com reposição, prob. equivalentes
```{r}
# Este código em R cria uma amostra de 150 valores aleatórios com substituição, escolhendo entre os números 0 e 1 com probabilidades iguais (50% para cada). Em seguida, ele converte a amostra em um fator e gera um resumo estatístico das contagens de cada categoria (0 e 1) na amostra.

amostra = sample(c(0,1), 150, replace = TRUE, prob=c(0.5,0.5))
amostra
summary(as.factor(amostra))
```
150 amostras, de zero e 1, com reposição, mais chances para zero
```{r}
# Esse código em R gera uma amostra de 150 elementos, onde os valores 0 e 1 são escolhidos com substituição (replace = TRUE), com probabilidades de 70% para 0 e 30% para 1. Em seguida, ele converte a amostra em um fator e exibe um resumo estatístico que mostra a contagem de cada valor na amostra.

amostra = sample(c(0,1), 150, replace = TRUE, prob=c(0.7,0.3))
amostra
summary(as.factor(amostra))
```
150 amostras, de 1 a 1000, sem reposição, prob. equivalentes
```{r}
# Este código em R cria uma amostra aleatória de 150 números distintos no intervalo de 1 a 1000, sem substituição, ou seja, cada número aparece apenas uma vez na amostra. A segunda linha exibe a amostra gerada.

amostra = sample(c(1:1000), 150, replace = FALSE)
amostra
```
Gerado amostra de conjuntos de dados
30% dos dados de iris
```{r}
# Este código em R gera uma amostra de 150 números, onde cada número pode ser 0 ou 1, com substituição. A probabilidade de escolher 0 é de 70% e a probabilidade de escolher 1 é de 30%. Em seguida, ele resume essa amostra, mostrando a contagem de cada valor (0 e 1) na forma de um resumo de fatores.

amostra = sample(c(0,1), 150, replace = TRUE, prob=c(0.7,0.3))
summary(as.factor(amostra))
```
Gera a amostra
```{r}
# O código em questão cria um novo conjunto de dados chamado 'amostrairis' selecionando apenas as linhas da matriz 'iris' onde a variável 'amostra' tem o valor igual a 1. Em seguida, ele exibe esse novo conjunto de dados e também a dimensão (número de linhas e colunas) do 'amostrairis'.

amostrairis = iris[amostra==1,]
amostrairis
dim(amostrairis)
```
Repetir experimento
```{r}
# Este código em R começa definindo uma semente para geração de números aleatórios com `set.seed(2345)`. Em seguida, ele usa a função `sample` para gerar uma amostra aleatória de tamanho 1 a partir do conjunto contendo apenas o número 1000. O resultado será um único número aleatório, que pode variar dependendo da semente estabelecida.

set.seed(2345)
sample(c(1000), 1)
```
Repetindo
```{r}
# Este código em R começa definindo uma semente para geração de números aleatórios com `set.seed(2345)`. Em seguida, ele usa a função `sample` para gerar uma amostra aleatória de tamanho 1 a partir do conjunto contendo apenas o número 1000. O resultado será um único número aleatório, que pode variar dependendo da semente estabelecida.

set.seed(2345)
sample(c(1000), 1)
```
