---
Formação Cientista de Dados
Limpeza e Tratamento de Dados
---

```{r}
# Este código em R lê um arquivo chamado "Tempo.csv" usando ponto e vírgula como separador, converte valores vazios em dados ausentes, e cria fatores a partir de colunas de texto. Em seguida, exibe as primeiras linhas e um resumo estatístico dos dados do arquivo.

# Importa dados, string vazio como NA, string como fatores
dados = read.csv("Tempo.csv", sep = ";", na.strings="", stringsAsFactors=T)
head(dados)
summary(dados)
```
Explorar Dados, Aparência
```{r}
# O código analisa três variáveis diferentes ("Aparência", "Vento" e "Jogar") em um conjunto de dados chamado "dados". Ele conta quantas vezes cada valor único aparece em cada variável e cria gráficos de barras individuais para representar essas contagens, onde o título de cada gráfico é o nome da variável e o eixo x representa os diferentes valores únicos da variável.

# Aparencia
counts = table(dados$Aparencia)
counts
barplot(counts, main="Aparencia", xlab="Aparencia")

# Gênero
counts = table(dados$Vento)
counts
barplot(counts, main="Vento", xlab="Vento")

#jogar
counts = table(dados$Jogar)
counts
barplot(counts, main="Jogar", xlab="Jogar")
```
Explorar, colunas numéricas
```{r}
# O código em R analisa um conjunto de dados chamado "dados". Ele calcula um resumo estatístico da variável "Temperatura", mostrando valores como média e quartis. Depois, cria um gráfico de caixa (boxplot) para representar a distribuição dessa variável e um histograma para mostrar a frequência dos diferentes valores de temperatura no conjunto de dados.

# Temperatura
summary(dados$Temperatura)
boxplot(dados$Temperatura)
hist(dados$Temperatura)
```
Umidade
```{r}
# Esse código R resume estatísticas da coluna "Umidade" dos seus dados, mostrando a média, mediana e outros valores. Depois, cria um gráfico de caixa que apresenta a distribuição dessa coluna. Por fim, gera um histograma para ilustrar como os valores de umidade estão distribuídos.

summary(dados$Umidade)
boxplot(dados$Umidade)
hist(dados$Umidade)
```
Valore faltantes - NAs
```{r}
# O código R verifica uma estrutura de dados chamada 'dados' em busca de linhas que possuam valores faltantes (NAs) em pelo menos uma coluna. Em seguida, ele retorna as linhas que contêm esses valores faltantes, mostrando onde eles estão presentes na tabela.

# Valores faltantes NAs
dados[!complete.cases(dados),]
```
Aparência, tratar dominio
```{r}
# O código analisa uma variável chamada "Aparencia" em um conjunto de dados chamado "dados". 

# Primeiro, ele exibe um resumo estatístico dessa variável.
summary(dados$Aparencia)

# Em seguida, ele identifica e exibe as linhas com valores ausentes ("NAs") na variável "Aparencia".
dados[is.na(dados$Aparencia),]

# Depois, ele substitui os valores "menos" por "sol" na variável "Aparencia".
dados[dados$Aparencia == 'menos' ,]$Aparencia = 'sol' 

# Outro resumo estatístico é exibido.
summary(dados$Aparencia)

# O código então transforma a variável "Aparencia" em um fator e mostra novamente um resumo. Isso é feito para remover níveis não utilizados na variável categórica e para verificar as mudanças feitas.
dados$Aparencia =   factor(dados$Aparencia)

# Visualizar novamente
summary(dados$Aparencia)
```
Temperatura - tratar dominio
```{r}
# Esse código R analisa dados de temperatura. 

# Primeiro, ele mostra um resumo estatístico das temperaturas.
summary(dados$Temperatura)

# Em seguida, identifica e exibe valores de temperatura que estão fora do intervalo normal (-130 a 130).
dados[dados$Temperatura < -130 | dados$Temperatura > 130 ,]$Temperatura

# Depois, verifica se existem valores ausentes (NA) nas temperaturas.
dados[is.na(dados$Temperatura),]

# A opção é preencher os valores ausentes com a mediana das temperaturas.
median(dados$Temperatura)

# Em seguida, substitui os valores extremos abaixo de -135 e acima de 130 pela mediana.
dados[dados$Temperatura < -135 | dados$Temperatura > 130 ,]$Temperatura = median(dados$Temperatura) 

# Por fim, o código verifica novamente e exibe temperaturas anormais e um novo resumo estatístico das temperaturas.
dados[dados$Temperatura< -135 | dados$Temperatura > 130 ,]$Temperatura
summary(dados$Temperatura)
```
Umidade, dominio e NAs
```{r}
# Este código R analisa a coluna "Umidade" de um conjunto de dados. 

# Ele começa mostrando um resumo estatístico dessa coluna.
summary(dados$Umidade)

# Em seguida, identifica e exibe os valores de umidade que estão fora do intervalo normal (menores que 0 ou maiores que 100).
dados[dados$Umidade < 0 | dados$Umidade > 100 ,]$Umidade

# Depois, ele verifica se existem valores ausentes (NA) na coluna de umidade e os exibe.
dados[is.na(dados$Umidade),]

# Posteriormente, preenche os valores ausentes com a mediana da umidade, calculada sem considerar os valores ausentes.
dados[is.na(dados$Umidade),]$Umidade = median(dados$Umidade,na.rm = T)

#  Após isso, substitui novamente os valores de umidade que estão fora do intervalo normal pela mediana geral da umidade.
dados[dados$Umidade < 0 | dados$Umidade > 100 ,]$Umidade = median(dados$Umidade) 

# Por fim, busca novamente e mostra quaisquer valores de umidade anormais que possam ainda existir, e apresenta outro resumo estatístico da coluna "Umidade".
dados[dados$Umidade < 0 | dados$Umidade > 100 ,]
summary(dados$Umidade)
```
Vento NAs
```{r}
# O código analisa uma coluna chamada "Vento" em um conjunto de dados. 

# Primeiro, ele resume estatísticas dessa coluna.
summary(dados$Vento)

# Em seguida, verifica se existem valores ausentes (NAs) nessa coluna e exibe as linhas que possuem esses valores ausentes.
dados[is.na(dados$Vento),]

# Depois, substitui os valores ausentes na coluna "Vento" por 'FALSO'.
dados[is.na(dados$Vento),]$Vento = 'FALSO'

# O código verifica novamente se ainda existem valores ausentes na coluna "Vento" e exibe as linhas correspondentes.
dados[is.na(dados$Vento),]

# Por fim, ele apresenta um resumo atualizado das estatísticas da coluna "Vento".
summary(dados$Vento)
```
