---
Formação Cientista de Dados
Faça você mesmo
---

```{r}
# Este código em R carrega a biblioteca "RColorBrewer", que é usada para criar paletas de cores personalizadas em gráficos.

library("RColorBrewer")

#install.packages("RColorBrewer")
```


```{r}
# Esse código em R lê um arquivo CSV chamado 'dados.csv' com ponto e vírgula como separador e em seguida mostra as primeiras linhas desse arquivo usando a função 'head'.

dados = read.csv('dados.csv', sep=";")
head(dados)
```


```{r}
# Os comandos "summary(dados$VALOREMPENHO)" e "summary(dados$PIB)" são utilizados para gerar um resumo estatístico das variáveis "VALOREMPENHO" e "PIB" contidas no conjunto de dados "dados". Isso inclui estatísticas como média, mediana, mínimo, máximo e quartis para cada uma dessas variáveis.

summary(dados$VALOREMPENHO)
summary(dados$PIB)
```


```{r warning=FALSE}
# Esse código em R cria quatro gráficos diferentes usando os dados contidos em duas variáveis, VALOREMPENHO e PIB, de um objeto chamado "dados". Ele cria dois gráficos de caixa (boxplot) e dois histogramas, utilizando paletas de cores específicas ("Paired" e "Pastel1") para cada conjunto de gráficos. Além disso, desabilita a exibição de valores extremos nos gráficos de caixa usando "outline = F". Os gráficos têm títulos relacionados aos dados que representam.

boxplot(dados$VALOREMPENHO, main="Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"), outline = F )
boxplot(dados$PIB ,main="Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F )
hist(dados$VALOREMPENHO,main="Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"))
hist(dados$PIB,main="Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F )
```


```{r}
# Ele ordena os dados pela coluna "VALOREMPENHO" em ordem decrescente e seleciona as 10 primeiras linhas, armazenando esse resultado na variável "Mempenho". Em seguida, cria um gráfico de barras (barplot) usando os valores da coluna "VALOREMPENHO" de "Mempenho". As barras são coloridas usando uma paleta de cores da biblioteca "RColorBrewer" com 10 cores, e o título do gráfico é definido como "Maiores Empenhos". Adiciona uma legenda no canto superior direito do gráfico com os nomes dos municípios contidos na coluna "MUNICIPIO" de "Mempenho". As cores da legenda correspondem às cores das barras do gráfico. Por fim, adiciona uma caixa em torno do gráfico usando a função "box()".

Mempenho = head(dados[order(-dados$VALOREMPENHO),],10)
barplot(Mempenho$VALOREMPENHO, col=brewer.pal(n = 10, name = "RdBu"),las=2,main = "Maiores Empenhos")
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "RdBu"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


```{r}
# Esse código em R realiza as seguintes ações em até 3 frases: 1. Seleciona as 10 primeiras linhas do dataframe 'dados' com os maiores valores de PIB e armazena em 'Mpibs'. 2. Cria um gráfico de barras (barplot) usando os valores de PIB de 'Mpibs' com cores definidas pela paleta "Spectral". 3. Adiciona uma legenda no canto superior direito do gráfico com os nomes dos municípios de 'Mempenho$MUNICIPIO' usando as mesmas cores da paleta "Spectral" e formatando a legenda. O código não é totalmente claro, pois faz referência a objetos não definidos (como 'dados' e 'Mempenho'), e alguns detalhes do contexto estão ausentes para uma compreensão completa.

Mpibs =   head(dados[order(-dados$PIB),],10)
barplot(Mpibs$PIB,col=brewer.pal(n = 10, name = "Spectral"),las=2,main = "Maiores PIBS")
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "Spectral"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


```{r}
# Esse código em R realiza as seguintes ações em até três frases: Calcula a proporção entre a coluna VALOREMPENHO e PIB no conjunto de dados 'dados' e armazena os resultados na coluna PROPORCAO. Seleciona as 10 linhas com as maiores proporções e armazena-as em 'Mprop'. Cria um gráfico de barras ('barplot') mostrando as proporções dessas 10 linhas em cores diferentes, com um título indicando "Maiores Gastos em Proporção ao PIB", adiciona uma legenda ('legend') com os nomes dos municípios correspondentes e uma caixa ao redor do gráfico ('box()').

dados$PROPORCAO =   dados$VALOREMPENHO  / dados$PIB 
Mprop = head(dados[order(-dados$PROPORCAO),],10)
barplot(Mprop$PROPORCAO,col=brewer.pal(n = 10, name = "Set2"),las=2,main = "Maiores Gastos em Proporção ao PIB")
legend("topright",legend=Mprop$MUNICIPIO,col = brewer.pal(n = 10, name = "Set2"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()

```
